export enum ChatV2ChannelType {
  MODEL_MATCHING = "modelMatching",
  HAIR_CONSULTATION = "hairConsultation",
  REVIEW_SPECIAL = "reviewSpecial",
  JOB_POSTING = "jobPosting",
}

export enum ChatV2PostType {
  MODEL_ANNOUNCEMENT = "MODEL_ANNOUNCEMENT",
  QUICK_MATCHING_PREMIUM = "QUICK_MATCHING_PREMIUM",
  QUICK_MATCHING_GENERAL = "QUICK_MATCHING_GENERAL",
  EXPERIENCE_GROUP = "EXPERIENCE_GROUP",
  CHAT = "CHAT",
  HAIR_CONSULTATION = "HAIR_CONSULTATION",
  REVIEW_SPECIAL = "REVIEW_SPECIAL",
  JOB_POSTING = "JOB_POSTING",
  RESUME = "RESUME",
}

export enum ChatOriginEntrySource {
  MODEL_ANNOUNCEMENT_DETAIL_APPLY_CHAT = "MODEL_ANNOUNCEMENT_DETAIL_APPLY_CHAT",
  QUICK_MATCHING_GENERAL_DETAIL_CHAT = "QUICK_MATCHING_GENERAL_DETAIL_CHAT",
  QUICK_MATCHING_PREMIUM_DETAIL_CHAT = "QUICK_MATCHING_PREMIUM_DETAIL_CHAT",
  EXPERIENCE_GROUP_DETAIL_CHAT = "EXPERIENCE_GROUP_DETAIL_CHAT",
  HAIR_CONSULTATION_POST_COMMENT_DIRECT_CHAT = "HAIR_CONSULTATION_POST_COMMENT_DIRECT_CHAT",
  HAIR_CONSULTATION_POST_COMMENT_DESIGNER_PROFILE_MENU_INQUIRY = "HAIR_CONSULTATION_POST_COMMENT_DESIGNER_PROFILE_MENU_INQUIRY",
  HAIR_CONSULTATION_RESPONSE_DETAIL_DIRECT_CHAT = "HAIR_CONSULTATION_RESPONSE_DETAIL_DIRECT_CHAT",
  HAIR_CONSULTATION_RESPONSE_DETAIL_DESIGNER_PROFILE_MENU_INQUIRY = "HAIR_CONSULTATION_RESPONSE_DETAIL_DESIGNER_PROFILE_MENU_INQUIRY",
  REVIEW_SPECIAL_RESERVATION_ACCEPT_CHAT = "REVIEW_SPECIAL_RESERVATION_ACCEPT_CHAT",
  JOB_POSTING_DETAIL_APPLY_CHAT = "JOB_POSTING_DETAIL_APPLY_CHAT",
  RESUME_DETAIL_OFFER_CHAT = "RESUME_DETAIL_OFFER_CHAT",
  MODEL_PROFILE_DIRECT_CHAT = "MODEL_PROFILE_DIRECT_CHAT",
  DESIGNER_PROFILE_MENU_INQUIRY = "DESIGNER_PROFILE_MENU_INQUIRY",
  RECENT_ACCESS_RECOMMENDED_MODEL_PROFILE_CHAT = "RECENT_ACCESS_RECOMMENDED_MODEL_PROFILE_CHAT",
  NEW_MODEL_PROFILE_CHAT = "NEW_MODEL_PROFILE_CHAT",
  RECENT_FEMALE_MODEL_PROFILE_CHAT = "RECENT_FEMALE_MODEL_PROFILE_CHAT",
  RECENT_MALE_MODEL_PROFILE_CHAT = "RECENT_MALE_MODEL_PROFILE_CHAT",
  NEARBY_MODEL_PROFILE_CHAT = "NEARBY_MODEL_PROFILE_CHAT",
  BEAUTY_MODEL_PROFILE_CHAT = "BEAUTY_MODEL_PROFILE_CHAT",
  ACTIVE_MODEL_PROFILE_CHAT = "ACTIVE_MODEL_PROFILE_CHAT",
  FAVORITE_MODEL_PROFILE_CHAT = "FAVORITE_MODEL_PROFILE_CHAT",
  QUICK_MATCHING_GENERAL_MODEL_PROFILE_CHAT = "QUICK_MATCHING_GENERAL_MODEL_PROFILE_CHAT",
  QUICK_MATCHING_PREMIUM_MODEL_PROFILE_CHAT = "QUICK_MATCHING_PREMIUM_MODEL_PROFILE_CHAT",
  TOP_ADVISOR_DESIGNER_PROFILE_MENU_INQUIRY = "TOP_ADVISOR_DESIGNER_PROFILE_MENU_INQUIRY",
  RECOMMENDER_DESIGNER_PROFILE_MENU_INQUIRY = "RECOMMENDER_DESIGNER_PROFILE_MENU_INQUIRY",
  NO_FACE_SHOOTING_DESIGNER_PROFILE_MENU_INQUIRY = "NO_FACE_SHOOTING_DESIGNER_PROFILE_MENU_INQUIRY",
  SEARCH_MAP_DESIGNER_PROFILE_MENU_INQUIRY = "SEARCH_MAP_DESIGNER_PROFILE_MENU_INQUIRY",
  FAVORITE_NOTIFICATION_MODEL_PROFILE_CHAT = "FAVORITE_NOTIFICATION_MODEL_PROFILE_CHAT",
  HAIR_CONSULTATION_ANSWER_NOTIFICATION_MODEL_PROFILE_CHAT = "HAIR_CONSULTATION_ANSWER_NOTIFICATION_MODEL_PROFILE_CHAT",
  STORELINK_NOTIFICATION_MODEL_PROFILE_CHAT = "STORELINK_NOTIFICATION_MODEL_PROFILE_CHAT",
  INSTAGRAM_NOTIFICATION_MODEL_PROFILE_CHAT = "INSTAGRAM_NOTIFICATION_MODEL_PROFILE_CHAT",
}

export enum ChatOriginPricingType {
  PAY = "pay",
  NEW = "new",
  RECENT_FEMALE = "recent_female",
  RECENT_MALE = "recent_male",
  LONG_TIME = "longTime",
  BEAUTY = "beauty",
  FAVORITE = "favorite",
  THUNDER_DEFAULT = "thunder_default",
}

export type ChatStartRequest = {
  channelType: ChatV2ChannelType;
  postType: ChatV2PostType;
  postId: string;
  targetUserId: string;
  originEntrySource: ChatOriginEntrySource;
  originPricingType?: ChatOriginPricingType | null;
  answerId?: string;
  joinType?: "MODEL" | "DESIGNER";
  isMyHairConsultationPost?: boolean;
  targetDisplayName?: string;
};
