type SiSggList = Record<
  string,
  { key: string; value: string; viewString: string }[]
>;

export const siNmShort = [
  { key: "서울특별시", value: "서울" },
  { key: "부산광역시", value: "부산" },
  { key: "대구광역시", value: "대구" },
  { key: "인천광역시", value: "인천" },
  { key: "광주광역시", value: "광주" },
  { key: "대전광역시", value: "대전" },
  { key: "울산광역시", value: "울산" },
  { key: "세종특별자치시", value: "세종" },
  { key: "경기도", value: "경기" },
  { key: "충청북도", value: "충북" },
  { key: "충청남도", value: "충남" },
  { key: "전라북도", value: "전북" },
  { key: "전라남도", value: "전남" },
  { key: "경상북도", value: "경북" },
  { key: "경상남도", value: "경남" },
  { key: "제주특별자치도", value: "제주" },
  { key: "강원특별자치", value: "강원" },
];

export const siSggList: SiSggList = {
  서울특별시: [
    { key: "서울특별시 전체", value: "서울 전체", viewString: "서울 전체" },
    { key: "서울특별시 종로구", value: "종로구", viewString: "서울 종로구" },
    { key: "서울특별시 중구", value: "중구", viewString: "서울 중구" },
    { key: "서울특별시 용산구", value: "용산구", viewString: "서울 용산구" },
    { key: "서울특별시 성동구", value: "성동구", viewString: "서울 성동구" },
    { key: "서울특별시 광진구", value: "광진구", viewString: "서울 광진구" },
    {
      key: "서울특별시 동대문구",
      value: "동대문구",
      viewString: "서울 동대문구",
    },
    { key: "서울특별시 중랑구", value: "중랑구", viewString: "서울 중랑구" },
    { key: "서울특별시 성북구", value: "성북구", viewString: "서울 성북구" },
    { key: "서울특별시 강북구", value: "강북구", viewString: "서울 강북구" },
    { key: "서울특별시 도봉구", value: "도봉구", viewString: "서울 도봉구" },
    { key: "서울특별시 노원구", value: "노원구", viewString: "서울 노원구" },
    { key: "서울특별시 은평구", value: "은평구", viewString: "서울 은평구" },
    {
      key: "서울특별시 서대문구",
      value: "서대문구",
      viewString: "서울 서대문구",
    },
    { key: "서울특별시 마포구", value: "마포구", viewString: "서울 마포구" },
    { key: "서울특별시 양천구", value: "양천구", viewString: "서울 양천구" },
    { key: "서울특별시 강서구", value: "강서구", viewString: "서울 강서구" },
    { key: "서울특별시 구로구", value: "구로구", viewString: "서울 구로구" },
    { key: "서울특별시 금천구", value: "금천구", viewString: "서울 금천구" },
    {
      key: "서울특별시 영등포구",
      value: "영등포구",
      viewString: "서울 영등포구",
    },
    { key: "서울특별시 동작구", value: "동작구", viewString: "서울 동작구" },
    { key: "서울특별시 관악구", value: "관악구", viewString: "서울 관악구" },
    { key: "서울특별시 서초구", value: "서초구", viewString: "서울 서초구" },
    { key: "서울특별시 강남구", value: "강남구", viewString: "서울 강남구" },
    { key: "서울특별시 송파구", value: "송파구", viewString: "서울 송파구" },
    { key: "서울특별시 강동구", value: "강동구", viewString: "서울 강동구" },
  ],
  부산광역시: [
    { key: "부산광역시 전체", value: "부산 전체", viewString: "부산 전체" },
    { key: "부산광역시 중구", value: "중구", viewString: "부산 중구" },
    { key: "부산광역시 서구", value: "서구", viewString: "부산 서구" },
    { key: "부산광역시 동구", value: "동구", viewString: "부산 동구" },
    { key: "부산광역시 영도구", value: "영도구", viewString: "부산 영도구" },
    {
      key: "부산광역시 부산진구",
      value: "부산진구",
      viewString: "부산 부산진구",
    },
    { key: "부산광역시 동래구", value: "동래구", viewString: "부산 동래구" },
    { key: "부산광역시 남구", value: "남구", viewString: "부산 남구" },
    { key: "부산광역시 북구", value: "북구", viewString: "부산 북구" },
    {
      key: "부산광역시 해운대구",
      value: "해운대구",
      viewString: "부산 해운대구",
    },
    { key: "부산광역시 사하구", value: "사하구", viewString: "부산 사하구" },
    { key: "부산광역시 금정구", value: "금정구", viewString: "부산 금정구" },
    { key: "부산광역시 강서구", value: "강서구", viewString: "부산 강서구" },
    { key: "부산광역시 연제구", value: "연제구", viewString: "부산 연제구" },
    { key: "부산광역시 수영구", value: "수영구", viewString: "부산 수영구" },
    { key: "부산광역시 사상구", value: "사상구", viewString: "부산 사상구" },
    { key: "부산광역시 기장군", value: "기장군", viewString: "부산 기장군" },
  ],
  대구광역시: [
    { key: "대구광역시 전체", value: "대구 전체", viewString: "대구 전체" },
    { key: "대구광역시 중구", value: "중구", viewString: "대구 중구" },
    { key: "대구광역시 동구", value: "동구", viewString: "대구 동구" },
    { key: "대구광역시 서구", value: "서구", viewString: "대구 서구" },
    { key: "대구광역시 남구", value: "남구", viewString: "대구 남구" },
    { key: "대구광역시 북구", value: "북구", viewString: "대구 북구" },
    { key: "대구광역시 수성구", value: "수성구", viewString: "대구 수성구" },
    { key: "대구광역시 달서구", value: "달서구", viewString: "대구 달서구" },
    { key: "대구광역시 달성군", value: "달성군", viewString: "대구 달성군" },
    { key: "대구광역시 군위군", value: "군위군", viewString: "대구 군위군" },
  ],
  인천광역시: [
    { key: "인천광역시 전체", value: "인천 전체", viewString: "인천 전체" },
    { key: "인천광역시 중구", value: "중구", viewString: "인천 중구" },
    { key: "인천광역시 동구", value: "동구", viewString: "인천 동구" },
    {
      key: "인천광역시 미추홀구",
      value: "미추홀구",
      viewString: "인천 미추홀구",
    },
    { key: "인천광역시 연수구", value: "연수구", viewString: "인천 연수구" },
    { key: "인천광역시 남동구", value: "남동구", viewString: "인천 남동구" },
    { key: "인천광역시 부평구", value: "부평구", viewString: "인천 부평구" },
    { key: "인천광역시 계양구", value: "계양구", viewString: "인천 계양구" },
    { key: "인천광역시 서구", value: "서구", viewString: "인천 서구" },
    { key: "인천광역시 강화군", value: "강화군", viewString: "인천 강화군" },
    { key: "인천광역시 옹진군", value: "옹진군", viewString: "인천 옹진군" },
  ],
  광주광역시: [
    { key: "광주광역시 전체", value: "광주 전체", viewString: "광주 전체" },
    { key: "광주광역시 동구", value: "동구", viewString: "광주 동구" },
    { key: "광주광역시 서구", value: "서구", viewString: "광주 서구" },
    { key: "광주광역시 남구", value: "남구", viewString: "광주 남구" },
    { key: "광주광역시 북구", value: "북구", viewString: "광주 북구" },
    { key: "광주광역시 광산구", value: "광산구", viewString: "광주 광산구" },
  ],
  대전광역시: [
    { key: "대전광역시 전체", value: "대전 전체", viewString: "대전 전체" },
    { key: "대전광역시 동구", value: "동구", viewString: "대전 동구" },
    { key: "대전광역시 중구", value: "중구", viewString: "대전 중구" },
    { key: "대전광역시 서구", value: "서구", viewString: "대전 서구" },
    { key: "대전광역시 유성구", value: "유성구", viewString: "대전 유성구" },
    { key: "대전광역시 대덕구", value: "대덕구", viewString: "대전 대덕구" },
  ],
  울산광역시: [
    { key: "울산광역시 전체", value: "울산 전체", viewString: "울산 전체" },
    { key: "울산광역시 중구", value: "중구", viewString: "울산 중구" },
    { key: "울산광역시 남구", value: "남구", viewString: "울산 남구" },
    { key: "울산광역시 동구", value: "동구", viewString: "울산 동구" },
    { key: "울산광역시 북구", value: "북구", viewString: "울산 북구" },
    { key: "울산광역시 울주군", value: "울주군", viewString: "울산 울주군" },
  ],
  세종특별자치시: [
    {
      key: "세종특별자치시 전체",
      value: "세종시 전체",
      viewString: "세종 전체",
    },
  ],
  경기도: [
    { key: "경기도 전체", value: "경기 전체", viewString: "경기 전체" },
    { key: "경기도 수원시", value: "수원시", viewString: "경기 수원시" },
    {
      key: "경기도 수원시 장안구",
      value: "수원시 장안구",
      viewString: "경기 수원시 장안구",
    },
    {
      key: "경기도 수원시 권선구",
      value: "수원시 권선구",
      viewString: "경기 수원시 권선구",
    },
    {
      key: "경기도 수원시 팔달구",
      value: "수원시 팔달구",
      viewString: "경기 수원시 팔달구",
    },
    {
      key: "경기도 수원시 영통구",
      value: "수원시 영통구",
      viewString: "경기 수원시 영통구",
    },
    { key: "경기도 성남시", value: "성남시", viewString: "경기 성남시" },
    {
      key: "경기도 성남시 수정구",
      value: "성남시 수정구",
      viewString: "경기 성남시 수정구",
    },
    {
      key: "경기도 성남시 중원구",
      value: "성남시 중원구",
      viewString: "경기 성남시 중원구",
    },
    {
      key: "경기도 성남시 분당구",
      value: "성남시 분당구",
      viewString: "경기 성남시 분당구",
    },
    { key: "경기도 의정부시", value: "의정부시", viewString: "경기 의정부시" },
    { key: "경기도 안양시", value: "안양시", viewString: "경기 안양시" },
    {
      key: "경기도 안양시 만안구",
      value: "안양시 만안구",
      viewString: "경기 안양시 만안구",
    },
    {
      key: "경기도 안양시 동안구",
      value: "안양시 동안구",
      viewString: "경기 안양시 동안구",
    },
    { key: "경기도 부천시", value: "부천시", viewString: "경기 부천시" },
    { key: "경기도 광명시", value: "광명시", viewString: "경기 광명시" },
    { key: "경기도 평택시", value: "평택시", viewString: "경기 평택시" },
    { key: "경기도 동두천시", value: "동두천시", viewString: "경기 동두천시" },
    { key: "경기도 안산시", value: "안산시", viewString: "경기 안산시" },
    { key: "경기도 고양시", value: "고양시", viewString: "경기 고양시" },
    { key: "경기도 과천시", value: "과천시", viewString: "경기 과천시" },
    { key: "경기도 구리시", value: "구리시", viewString: "경기 구리시" },
    { key: "경기도 남양주시", value: "남양주시", viewString: "경기 남양주시" },
    { key: "경기도 오산시", value: "오산시", viewString: "경기 오산시" },
    { key: "경기도 시흥시", value: "시흥시", viewString: "경기 시흥시" },
    { key: "경기도 군포시", value: "군포시", viewString: "경기 군포시" },
    { key: "경기도 의왕시", value: "의왕시", viewString: "경기 의왕시" },
    { key: "경기도 하남시", value: "하남시", viewString: "경기 하남시" },
    { key: "경기도 용인시", value: "용인시", viewString: "경기 용인시" },
    { key: "경기도 파주시", value: "파주시", viewString: "경기 파주시" },
    { key: "경기도 이천시", value: "이천시", viewString: "경기 이천시" },
    { key: "경기도 안성시", value: "안성시", viewString: "경기 안성시" },
    { key: "경기도 김포시", value: "김포시", viewString: "경기 김포시" },
    { key: "경기도 화성시", value: "화성시", viewString: "경기 화성시" },
    { key: "경기도 광주시", value: "광주시", viewString: "경기 광주시" },
    { key: "경기도 양주시", value: "양주시", viewString: "경기 양주시" },
    { key: "경기도 포천시", value: "포천시", viewString: "경기 포천시" },
    { key: "경기도 여주시", value: "여주시", viewString: "경기 여주시" },
  ],
  충청북도: [
    { key: "충청북도 전체", value: "충북 전체", viewString: "충북 전체" },
    { key: "충청북도 청주시", value: "청주시", viewString: "충북 청주시" },
    { key: "충청북도 충주시", value: "충주시", viewString: "충북 충주시" },
    { key: "충청북도 제천시", value: "제천시", viewString: "충북 제천시" },
    { key: "충청북도 보은군", value: "보은군", viewString: "충북 보은군" },
    { key: "충청북도 옥천군", value: "옥천군", viewString: "충북 옥천군" },
    { key: "충청북도 영동군", value: "영동군", viewString: "충북 영동군" },
    { key: "충청북도 증평군", value: "증평군", viewString: "충북 증평군" },
    { key: "충청북도 진천군", value: "진천군", viewString: "충북 진천군" },
    { key: "충청북도 괴산군", value: "괴산군", viewString: "충북 괴산군" },
    { key: "충청북도 음성군", value: "음성군", viewString: "충북 음성군" },
    { key: "충청북도 단양군", value: "단양군", viewString: "충북 단양군" },
  ],
  충청남도: [
    { key: "충청남도 전체", value: "충남 전체", viewString: "충남 전체" },
    { key: "충청남도 천안시", value: "천안시", viewString: "충남 천안시" },
    { key: "충청남도 공주시", value: "공주시", viewString: "충남 공주시" },
    { key: "충청남도 보령시", value: "보령시", viewString: "충남 보령시" },
    { key: "충청남도 아산시", value: "아산시", viewString: "충남 아산시" },
    { key: "충청남도 서산시", value: "서산시", viewString: "충남 서산시" },
    { key: "충청남도 논산시", value: "논산시", viewString: "충남 논산시" },
    { key: "충청남도 계룡시", value: "계룡시", viewString: "충남 계룡시" },
    { key: "충청남도 당진시", value: "당진시", viewString: "충남 당진시" },
    { key: "충청남도 금산군", value: "금산군", viewString: "충남 금산군" },
    { key: "충청남도 부여군", value: "부여군", viewString: "충남 부여군" },
    { key: "충청남도 서천군", value: "서천군", viewString: "충남 서천군" },
    { key: "충청남도 청양군", value: "청양군", viewString: "충남 청양군" },
    { key: "충청남도 홍성군", value: "홍성군", viewString: "충남 홍성군" },
    { key: "충청남도 예산군", value: "예산군", viewString: "충남 예산군" },
    { key: "충청남도 태안군", value: "태안군", viewString: "충남 태안군" },
  ],
  전라북도: [
    { key: "전라북도 전체", value: "전북 전체", viewString: "전북 전체" },
    { key: "전라북도 전주시", value: "전주시", viewString: "전북 전주시" },
    { key: "전라북도 군산시", value: "군산시", viewString: "전북 군산시" },
    { key: "전라북도 익산시", value: "익산시", viewString: "전북 익산시" },
    { key: "전라북도 정읍시", value: "정읍시", viewString: "전북 정읍시" },
    { key: "전라북도 남원시", value: "남원시", viewString: "전북 남원시" },
    { key: "전라북도 김제시", value: "김제시", viewString: "전북 김제시" },
    { key: "전라북도 완주군", value: "완주군", viewString: "전북 완주군" },
    { key: "전라북도 진안군", value: "진안군", viewString: "전북 진안군" },
    { key: "전라북도 무주군", value: "무주군", viewString: "전북 무주군" },
    { key: "전라북도 장수군", value: "장수군", viewString: "전북 장수군" },
    { key: "전라북도 임실군", value: "임실군", viewString: "전북 임실군" },
    { key: "전라북도 순창군", value: "순창군", viewString: "전북 순창군" },
    { key: "전라북도 고창군", value: "고창군", viewString: "전북 고창군" },
    { key: "전라북도 부안군", value: "부안군", viewString: "전북 부안군" },
  ],
  전라남도: [
    { key: "전라남도 전체", value: "전남 전체", viewString: "전남 전체" },
    { key: "전라남도 목포시", value: "목포시", viewString: "전남 목포시" },
    { key: "전라남도 여수시", value: "여수시", viewString: "전남 여수시" },
    { key: "전라남도 순천시", value: "순천시", viewString: "전남 순천시" },
    { key: "전라남도 나주시", value: "나주시", viewString: "전남 나주시" },
    { key: "전라남도 광양시", value: "광양시", viewString: "전남 광양시" },
    { key: "전라남도 담양군", value: "담양군", viewString: "전남 담양군" },
    { key: "전라남도 곡성군", value: "곡성군", viewString: "전남 곡성군" },
    { key: "전라남도 구례군", value: "구례군", viewString: "전남 구례군" },
    { key: "전라남도 고흥군", value: "고흥군", viewString: "전남 고흥군" },
    { key: "전라남도 보성군", value: "보성군", viewString: "전남 보성군" },
    { key: "전라남도 화순군", value: "화순군", viewString: "전남 화순군" },
    { key: "전라남도 장흥군", value: "장흥군", viewString: "전남 장흥군" },
    { key: "전라남도 강진군", value: "강진군", viewString: "전남 강진군" },
    { key: "전라남도 해남군", value: "해남군", viewString: "전남 해남군" },
    { key: "전라남도 영암군", value: "영암군", viewString: "전남 영암군" },
    { key: "전라남도 무안군", value: "무안군", viewString: "전남 무안군" },
    { key: "전라남도 함평군", value: "함평군", viewString: "전남 함평군" },
    { key: "전라남도 영광군", value: "영광군", viewString: "전남 영광군" },
    { key: "전라남도 장성군", value: "장성군", viewString: "전남 장성군" },
    { key: "전라남도 완도군", value: "완도군", viewString: "전남 완도군" },
    { key: "전라남도 진도군", value: "진도군", viewString: "전남 진도군" },
    { key: "전라남도 신안군", value: "신안군", viewString: "전남 신안군" },
  ],
  경상북도: [
    { key: "경상북도 전체", value: "경북 전체", viewString: "경북 전체" },
    { key: "경상북도 포항시", value: "포항시", viewString: "경북 포항시" },
    { key: "경상북도 경주시", value: "경주시", viewString: "경북 경주시" },
    { key: "경상북도 김천시", value: "김천시", viewString: "경북 김천시" },
    { key: "경상북도 안동시", value: "안동시", viewString: "경북 안동시" },
    { key: "경상북도 구미시", value: "구미시", viewString: "경북 구미시" },
    { key: "경상북도 영주시", value: "영주시", viewString: "경북 영주시" },
    { key: "경상북도 영천시", value: "영천시", viewString: "경북 영천시" },
    { key: "경상북도 상주시", value: "상주시", viewString: "경북 상주시" },
    { key: "경상북도 문경시", value: "문경시", viewString: "경북 문경시" },
    { key: "경상북도 경산시", value: "경산시", viewString: "경북 경산시" },
    { key: "경상북도 의성군", value: "의성군", viewString: "경북 의성군" },
    { key: "경상북도 청송군", value: "청송군", viewString: "경북 청송군" },
    { key: "경상북도 영양군", value: "영양군", viewString: "경북 영양군" },
    { key: "경상북도 영덕군", value: "영덕군", viewString: "경북 영덕군" },
    { key: "경상북도 청도군", value: "청도군", viewString: "경북 청도군" },
    { key: "경상북도 고령군", value: "고령군", viewString: "경북 고령군" },
    { key: "경상북도 성주군", value: "성주군", viewString: "경북 성주군" },
    { key: "경상북도 칠곡군", value: "칠곡군", viewString: "경북 칠곡군" },
    { key: "경상북도 예천군", value: "예천군", viewString: "경북 예천군" },
    { key: "경상북도 봉화군", value: "봉화군", viewString: "경북 봉화군" },
    { key: "경상북도 울진군", value: "울진군", viewString: "경북 울진군" },
    { key: "경상북도 울릉군", value: "울릉군", viewString: "경북 울릉군" },
  ],
  경상남도: [
    { key: "경상남도 전체", value: "경남 전체", viewString: "경남 전체" },
    { key: "경상남도 창원시", value: "창원시", viewString: "경남 창원시" },
    { key: "경상남도 진주시", value: "진주시", viewString: "경남 진주시" },
    { key: "경상남도 통영시", value: "통영시", viewString: "경남 통영시" },
    { key: "경상남도 사천시", value: "사천시", viewString: "경남 사천시" },
    { key: "경상남도 김해시", value: "김해시", viewString: "경남 김해시" },
    { key: "경상남도 밀양시", value: "밀양시", viewString: "경남 밀양시" },
    { key: "경상남도 거제시", value: "거제시", viewString: "경남 거제시" },
    { key: "경상남도 양산시", value: "양산시", viewString: "경남 양산시" },
    { key: "경상남도 의령군", value: "의령군", viewString: "경남 의령군" },
    { key: "경상남도 함안군", value: "함안군", viewString: "경남 함안군" },
    { key: "경상남도 창녕군", value: "창녕군", viewString: "경남 창녕군" },
    { key: "경상남도 고성군", value: "고성군", viewString: "경남 고성군" },
    { key: "경상남도 남해군", value: "남해군", viewString: "경남 남해군" },
    { key: "경상남도 하동군", value: "하동군", viewString: "경남 하동군" },
    { key: "경상남도 산청군", value: "산청군", viewString: "경남 산청군" },
    { key: "경상남도 함양군", value: "함양군", viewString: "경남 함양군" },
    { key: "경상남도 거창군", value: "거창군", viewString: "경남 거창군" },
    { key: "경상남도 합천군", value: "합천군", viewString: "경남 합천군" },
  ],
  제주특별자치도: [
    { key: "제주특별자치도 전체", value: "제주 전체", viewString: "제주 전체" },
    {
      key: "제주특별자치도 제주시",
      value: "제주시",
      viewString: "제주 제주시",
    },
    {
      key: "제주특별자치도 서귀포시",
      value: "서귀포시",
      viewString: "제주 서귀포시",
    },
  ],
};

export const locationKeysAndShorts = [
  { key: "서울특별시 종로구", value: "종로구", viewString: "서울 종로구" },
  { key: "서울특별시 중구", value: "중구", viewString: "서울 중구" },
  { key: "서울특별시 용산구", value: "용산구", viewString: "서울 용산구" },
  { key: "서울특별시 성동구", value: "성동구", viewString: "서울 성동구" },
  { key: "서울특별시 광진구", value: "광진구", viewString: "서울 광진구" },
  {
    key: "서울특별시 동대문구",
    value: "동대문구",
    viewString: "서울 동대문구",
  },
  { key: "서울특별시 중랑구", value: "중랑구", viewString: "서울 중랑구" },
  { key: "서울특별시 성북구", value: "성북구", viewString: "서울 성북구" },
  { key: "서울특별시 강북구", value: "강북구", viewString: "서울 강북구" },
  { key: "서울특별시 도봉구", value: "도봉구", viewString: "서울 도봉구" },
  { key: "서울특별시 노원구", value: "노원구", viewString: "서울 노원구" },
  { key: "서울특별시 은평구", value: "은평구", viewString: "서울 은평구" },
  {
    key: "서울특별시 서대문구",
    value: "서대문구",
    viewString: "서울 서대문구",
  },
  { key: "서울특별시 마포구", value: "마포구", viewString: "서울 마포구" },
  { key: "서울특별시 양천구", value: "양천구", viewString: "서울 양천구" },
  { key: "서울특별시 강서구", value: "강서구", viewString: "서울 강서구" },
  { key: "서울특별시 구로구", value: "구로구", viewString: "서울 구로구" },
  { key: "서울특별시 금천구", value: "금천구", viewString: "서울 금천구" },
  {
    key: "서울특별시 영등포구",
    value: "영등포구",
    viewString: "서울 영등포구",
  },
  { key: "서울특별시 동작구", value: "동작구", viewString: "서울 동작구" },
  { key: "서울특별시 관악구", value: "관악구", viewString: "서울 관악구" },
  { key: "서울특별시 서초구", value: "서초구", viewString: "서울 서초구" },
  { key: "서울특별시 강남구", value: "강남구", viewString: "서울 강남구" },
  { key: "서울특별시 송파구", value: "송파구", viewString: "서울 송파구" },
  { key: "서울특별시 강동구", value: "강동구", viewString: "서울 강동구" },
  { key: "부산광역시 중구", value: "중구", viewString: "부산 중구" },
  { key: "부산광역시 서구", value: "서구", viewString: "부산 서구" },
  { key: "부산광역시 동구", value: "동구", viewString: "부산 동구" },
  { key: "부산광역시 영도구", value: "영도구", viewString: "부산 영도구" },
  {
    key: "부산광역시 부산진구",
    value: "부산진구",
    viewString: "부산 부산진구",
  },
  { key: "부산광역시 동래구", value: "동래구", viewString: "부산 동래구" },
  { key: "부산광역시 남구", value: "남구", viewString: "부산 남구" },
  { key: "부산광역시 북구", value: "북구", viewString: "부산 북구" },
  {
    key: "부산광역시 해운대구",
    value: "해운대구",
    viewString: "부산 해운대구",
  },
  { key: "부산광역시 사하구", value: "사하구", viewString: "부산 사하구" },
  { key: "부산광역시 금정구", value: "금정구", viewString: "부산 금정구" },
  { key: "부산광역시 강서구", value: "강서구", viewString: "부산 강서구" },
  { key: "부산광역시 연제구", value: "연제구", viewString: "부산 연제구" },
  { key: "부산광역시 수영구", value: "수영구", viewString: "부산 수영구" },
  { key: "부산광역시 사상구", value: "사상구", viewString: "부산 사상구" },
  { key: "부산광역시 기장군", value: "기장군", viewString: "부산 기장군" },
  { key: "대구광역시 중구", value: "중구", viewString: "대구 중구" },
  { key: "대구광역시 동구", value: "동구", viewString: "대구 동구" },
  { key: "대구광역시 서구", value: "서구", viewString: "대구 서구" },
  { key: "대구광역시 남구", value: "남구", viewString: "대구 남구" },
  { key: "대구광역시 북구", value: "북구", viewString: "대구 북구" },
  { key: "대구광역시 수성구", value: "수성구", viewString: "대구 수성구" },
  { key: "대구광역시 달서구", value: "달서구", viewString: "대구 달서구" },
  { key: "대구광역시 달성군", value: "달성군", viewString: "대구 달성군" },
  { key: "대구광역시 군위군", value: "군위군", viewString: "대구 군위군" },
  { key: "인천광역시 중구", value: "중구", viewString: "인천 중구" },
  { key: "인천광역시 동구", value: "동구", viewString: "인천 동구" },
  {
    key: "인천광역시 미추홀구",
    value: "미추홀구",
    viewString: "인천 미추홀구",
  },
  { key: "인천광역시 연수구", value: "연수구", viewString: "인천 연수구" },
  { key: "인천광역시 남동구", value: "남동구", viewString: "인천 남동구" },
  { key: "인천광역시 부평구", value: "부평구", viewString: "인천 부평구" },
  { key: "인천광역시 계양구", value: "계양구", viewString: "인천 계양구" },
  { key: "인천광역시 서구", value: "서구", viewString: "인천 서구" },
  { key: "인천광역시 강화군", value: "강화군", viewString: "인천 강화군" },
  { key: "인천광역시 옹진군", value: "옹진군", viewString: "인천 옹진군" },
  { key: "광주광역시 동구", value: "동구", viewString: "광주 동구" },
  { key: "광주광역시 서구", value: "서구", viewString: "광주 서구" },
  { key: "광주광역시 남구", value: "남구", viewString: "광주 남구" },
  { key: "광주광역시 북구", value: "북구", viewString: "광주 북구" },
  { key: "광주광역시 광산구", value: "광산구", viewString: "광주 광산구" },
  { key: "대전광역시 동구", value: "동구", viewString: "대전 동구" },
  { key: "대전광역시 중구", value: "중구", viewString: "대전 중구" },
  { key: "대전광역시 서구", value: "서구", viewString: "대전 서구" },
  { key: "대전광역시 유성구", value: "유성구", viewString: "대전 유성구" },
  { key: "대전광역시 대덕구", value: "대덕구", viewString: "대전 대덕구" },
  { key: "울산광역시 중구", value: "중구", viewString: "울산 중구" },
  { key: "울산광역시 남구", value: "남구", viewString: "울산 남구" },
  { key: "울산광역시 동구", value: "동구", viewString: "울산 동구" },
  { key: "울산광역시 북구", value: "북구", viewString: "울산 북구" },
  { key: "울산광역시 울주군", value: "울주군", viewString: "울산 울주군" },
  { key: "경기도 수원시", value: "수원시", viewString: "경기 수원시" },
  {
    key: "경기도 수원시 장안구",
    value: "수원시 장안구",
    viewString: "경기 수원시 장안구",
  },
  {
    key: "경기도 수원시 권선구",
    value: "수원시 권선구",
    viewString: "경기 수원시 권선구",
  },
  {
    key: "경기도 수원시 팔달구",
    value: "수원시 팔달구",
    viewString: "경기 수원시 팔달구",
  },
  {
    key: "경기도 수원시 영통구",
    value: "수원시 영통구",
    viewString: "경기 수원시 영통구",
  },
  { key: "경기도 성남시", value: "성남시", viewString: "경기 성남시" },
  {
    key: "경기도 성남시 수정구",
    value: "성남시 수정구",
    viewString: "경기 성남시 수정구",
  },
  {
    key: "경기도 성남시 중원구",
    value: "성남시 중원구",
    viewString: "경기 성남시 중원구",
  },
  {
    key: "경기도 성남시 분당구",
    value: "성남시 분당구",
    viewString: "경기 성남시 분당구",
  },
  { key: "경기도 의정부시", value: "의정부시", viewString: "경기 의정부시" },
  { key: "경기도 안양시", value: "안양시", viewString: "경기 안양시" },
  {
    key: "경기도 안양시 만안구",
    value: "안양시 만안구",
    viewString: "경기 안양시 만안구",
  },
  {
    key: "경기도 안양시 동안구",
    value: "안양시 동안구",
    viewString: "경기 안양시 동안구",
  },
  { key: "경기도 부천시", value: "부천시", viewString: "경기 부천시" },
  { key: "경기도 광명시", value: "광명시", viewString: "경기 광명시" },
  { key: "경기도 평택시", value: "평택시", viewString: "경기 평택시" },
  { key: "경기도 동두천시", value: "동두천시", viewString: "경기 동두천시" },
  { key: "경기도 안산시", value: "안산시", viewString: "경기 안산시" },
  { key: "경기도 고양시", value: "고양시", viewString: "경기 고양시" },
  { key: "경기도 과천시", value: "과천시", viewString: "경기 과천시" },
  { key: "경기도 구리시", value: "구리시", viewString: "경기 구리시" },
  { key: "경기도 남양주시", value: "남양주시", viewString: "경기 남양주시" },
  { key: "경기도 오산시", value: "오산시", viewString: "경기 오산시" },
  { key: "경기도 시흥시", value: "시흥시", viewString: "경기 시흥시" },
  { key: "경기도 군포시", value: "군포시", viewString: "경기 군포시" },
  { key: "경기도 의왕시", value: "의왕시", viewString: "경기 의왕시" },
  { key: "경기도 하남시", value: "하남시", viewString: "경기 하남시" },
  { key: "경기도 용인시", value: "용인시", viewString: "경기 용인시" },
  { key: "경기도 파주시", value: "파주시", viewString: "경기 파주시" },
  { key: "경기도 이천시", value: "이천시", viewString: "경기 이천시" },
  { key: "경기도 안성시", value: "안성시", viewString: "경기 안성시" },
  { key: "경기도 김포시", value: "김포시", viewString: "경기 김포시" },
  { key: "경기도 화성시", value: "화성시", viewString: "경기 화성시" },
  { key: "경기도 광주시", value: "광주시", viewString: "경기 광주시" },
  { key: "경기도 양주시", value: "양주시", viewString: "경기 양주시" },
  { key: "경기도 포천시", value: "포천시", viewString: "경기 포천시" },
  { key: "경기도 여주시", value: "여주시", viewString: "경기 여주시" },
  { key: "충청북도 청주시", value: "청주시", viewString: "충북 청주시" },
  { key: "충청북도 충주시", value: "충주시", viewString: "충북 충주시" },
  { key: "충청북도 제천시", value: "제천시", viewString: "충북 제천시" },
  { key: "충청북도 보은군", value: "보은군", viewString: "충북 보은군" },
  { key: "충청북도 옥천군", value: "옥천군", viewString: "충북 옥천군" },
  { key: "충청북도 영동군", value: "영동군", viewString: "충북 영동군" },
  { key: "충청북도 증평군", value: "증평군", viewString: "충북 증평군" },
  { key: "충청북도 진천군", value: "진천군", viewString: "충북 진천군" },
  { key: "충청북도 괴산군", value: "괴산군", viewString: "충북 괴산군" },
  { key: "충청북도 음성군", value: "음성군", viewString: "충북 음성군" },
  { key: "충청북도 단양군", value: "단양군", viewString: "충북 단양군" },
  { key: "충청남도 천안시", value: "천안시", viewString: "충남 천안시" },
  { key: "충청남도 공주시", value: "공주시", viewString: "충남 공주시" },
  { key: "충청남도 보령시", value: "보령시", viewString: "충남 보령시" },
  { key: "충청남도 아산시", value: "아산시", viewString: "충남 아산시" },
  { key: "충청남도 서산시", value: "서산시", viewString: "충남 서산시" },
  { key: "충청남도 논산시", value: "논산시", viewString: "충남 논산시" },
  { key: "충청남도 계룡시", value: "계룡시", viewString: "충남 계룡시" },
  { key: "충청남도 당진시", value: "당진시", viewString: "충남 당진시" },
  { key: "충청남도 금산군", value: "금산군", viewString: "충남 금산군" },
  { key: "충청남도 부여군", value: "부여군", viewString: "충남 부여군" },
  { key: "충청남도 서천군", value: "서천군", viewString: "충남 서천군" },
  { key: "충청남도 청양군", value: "청양군", viewString: "충남 청양군" },
  { key: "충청남도 홍성군", value: "홍성군", viewString: "충남 홍성군" },
  { key: "충청남도 예산군", value: "예산군", viewString: "충남 예산군" },
  { key: "충청남도 태안군", value: "태안군", viewString: "충남 태안군" },
  { key: "전라북도 전주시", value: "전주시", viewString: "전북 전주시" },
  { key: "전라북도 군산시", value: "군산시", viewString: "전북 군산시" },
  { key: "전라북도 익산시", value: "익산시", viewString: "전북 익산시" },
  { key: "전라북도 정읍시", value: "정읍시", viewString: "전북 정읍시" },
  { key: "전라북도 남원시", value: "남원시", viewString: "전북 남원시" },
  { key: "전라북도 김제시", value: "김제시", viewString: "전북 김제시" },
  { key: "전라북도 완주군", value: "완주군", viewString: "전북 완주군" },
  { key: "전라북도 진안군", value: "진안군", viewString: "전북 진안군" },
  { key: "전라북도 무주군", value: "무주군", viewString: "전북 무주군" },
  { key: "전라북도 장수군", value: "장수군", viewString: "전북 장수군" },
  { key: "전라북도 임실군", value: "임실군", viewString: "전북 임실군" },
  { key: "전라북도 순창군", value: "순창군", viewString: "전북 순창군" },
  { key: "전라북도 고창군", value: "고창군", viewString: "전북 고창군" },
  { key: "전라북도 부안군", value: "부안군", viewString: "전북 부안군" },
  { key: "전라남도 목포시", value: "목포시", viewString: "전남 목포시" },
  { key: "전라남도 여수시", value: "여수시", viewString: "전남 여수시" },
  { key: "전라남도 순천시", value: "순천시", viewString: "전남 순천시" },
  { key: "전라남도 나주시", value: "나주시", viewString: "전남 나주시" },
  { key: "전라남도 광양시", value: "광양시", viewString: "전남 광양시" },
  { key: "전라남도 담양군", value: "담양군", viewString: "전남 담양군" },
  { key: "전라남도 곡성군", value: "곡성군", viewString: "전남 곡성군" },
  { key: "전라남도 구례군", value: "구례군", viewString: "전남 구례군" },
  { key: "전라남도 고흥군", value: "고흥군", viewString: "전남 고흥군" },
  { key: "전라남도 보성군", value: "보성군", viewString: "전남 보성군" },
  { key: "전라남도 화순군", value: "화순군", viewString: "전남 화순군" },
  { key: "전라남도 장흥군", value: "장흥군", viewString: "전남 장흥군" },
  { key: "전라남도 강진군", value: "강진군", viewString: "전남 강진군" },
  { key: "전라남도 해남군", value: "해남군", viewString: "전남 해남군" },
  { key: "전라남도 영암군", value: "영암군", viewString: "전남 영암군" },
  { key: "전라남도 무안군", value: "무안군", viewString: "전남 무안군" },
  { key: "전라남도 함평군", value: "함평군", viewString: "전남 함평군" },
  { key: "전라남도 영광군", value: "영광군", viewString: "전남 영광군" },
  { key: "전라남도 장성군", value: "장성군", viewString: "전남 장성군" },
  { key: "전라남도 완도군", value: "완도군", viewString: "전남 완도군" },
  { key: "전라남도 진도군", value: "진도군", viewString: "전남 진도군" },
  { key: "전라남도 신안군", value: "신안군", viewString: "전남 신안군" },
  { key: "경상북도 포항시", value: "포항시", viewString: "경북 포항시" },
  { key: "경상북도 경주시", value: "경주시", viewString: "경북 경주시" },
  { key: "경상북도 김천시", value: "김천시", viewString: "경북 김천시" },
  { key: "경상북도 안동시", value: "안동시", viewString: "경북 안동시" },
  { key: "경상북도 구미시", value: "구미시", viewString: "경북 구미시" },
  { key: "경상북도 영주시", value: "영주시", viewString: "경북 영주시" },
  { key: "경상북도 영천시", value: "영천시", viewString: "경북 영천시" },
  { key: "경상북도 상주시", value: "상주시", viewString: "경북 상주시" },
  { key: "경상북도 문경시", value: "문경시", viewString: "경북 문경시" },
  { key: "경상북도 경산시", value: "경산시", viewString: "경북 경산시" },
  { key: "경상북도 의성군", value: "의성군", viewString: "경북 의성군" },
  { key: "경상북도 청송군", value: "청송군", viewString: "경북 청송군" },
  { key: "경상북도 영양군", value: "영양군", viewString: "경북 영양군" },
  { key: "경상북도 영덕군", value: "영덕군", viewString: "경북 영덕군" },
  { key: "경상북도 청도군", value: "청도군", viewString: "경북 청도군" },
  { key: "경상북도 고령군", value: "고령군", viewString: "경북 고령군" },
  { key: "경상북도 성주군", value: "성주군", viewString: "경북 성주군" },
  { key: "경상북도 칠곡군", value: "칠곡군", viewString: "경북 칠곡군" },
  { key: "경상북도 예천군", value: "예천군", viewString: "경북 예천군" },
  { key: "경상북도 봉화군", value: "봉화군", viewString: "경북 봉화군" },
  { key: "경상북도 울진군", value: "울진군", viewString: "경북 울진군" },
  { key: "경상북도 울릉군", value: "울릉군", viewString: "경북 울릉군" },
  { key: "경상남도 창원시", value: "창원시", viewString: "경남 창원시" },
  { key: "경상남도 진주시", value: "진주시", viewString: "경남 진주시" },
  { key: "경상남도 통영시", value: "통영시", viewString: "경남 통영시" },
  { key: "경상남도 사천시", value: "사천시", viewString: "경남 사천시" },
  { key: "경상남도 김해시", value: "김해시", viewString: "경남 김해시" },
  { key: "경상남도 밀양시", value: "밀양시", viewString: "경남 밀양시" },
  { key: "경상남도 거제시", value: "거제시", viewString: "경남 거제시" },
  { key: "경상남도 양산시", value: "양산시", viewString: "경남 양산시" },
  { key: "경상남도 의령군", value: "의령군", viewString: "경남 의령군" },
  { key: "경상남도 함안군", value: "함안군", viewString: "경남 함안군" },
  { key: "경상남도 창녕군", value: "창녕군", viewString: "경남 창녕군" },
  { key: "경상남도 고성군", value: "고성군", viewString: "경남 고성군" },
  { key: "경상남도 남해군", value: "남해군", viewString: "경남 남해군" },
  { key: "경상남도 하동군", value: "하동군", viewString: "경남 하동군" },
  { key: "경상남도 산청군", value: "산청군", viewString: "경남 산청군" },
  { key: "경상남도 함양군", value: "함양군", viewString: "경남 함양군" },
  { key: "경상남도 거창군", value: "거창군", viewString: "경남 거창군" },
  { key: "경상남도 합천군", value: "합천군", viewString: "경남 합천군" },
  {
    key: "제주특별자치도 제주시",
    value: "제주시",
    viewString: "제주 제주시",
  },
  {
    key: "제주특별자치도 서귀포시",
    value: "서귀포시",
    viewString: "제주 서귀포시",
  },
];
